artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone
  local_data_file: artifacts/data_ingestion/ct-kidney-dataset-normal-cyst-tumor-and-stone.zip
  unzip_dir: artifacts/data_ingestion

data_processing:
    root_dir: artifacts/data_preparation
    data_in: artifacts/data_ingestion/X-ray_chest_images
    data_out: artifacts/data_preparation/processed_images
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_logs
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  